### Get all local
Get http://localhost:3000/weapons
### Get one local
Get http://localhost:3000/weapons/63dd586aaa7e0d80ef3b5b15
### Get one local
GET http://localhost:3000/weapons/63dd59b4aa7e0d80ef3b5b16
### Get one local
GET http://localhost:3000/weapons/63dd5a79aa7e0d80ef3b5b17

### Get all Render
GET https://web-backend-2.onrender.com/weapons
### Get one Render
GET https://w05-w08.onrender.com/weapons/63dd586aaa7e0d80ef3b5b15
### Get one Render
GET https://w05-w08.onrender.com/weapons/63dd59b4aa7e0d80ef3b5b16
### Get one Render
GET https://w05-w08.onrender.com/weapons/63dd5a79aa7e0d80ef3b5b17


### Create Weapon local
POST http://localhost:3000/weapons HTTP/1.1
Content-Type: application/json

{
    "name": "Sleeper Simulant",
    "gunPerkOne": "Polygonal Rifling",
    "gunPerkTwo": "Flared Magwell",
    "weaponPerkOne": "Moving Target",
    "weaponPerkTwo": "Composite Stock",
    "masterwork": "Catalyst",
    "originTrait": false,
    "mod": false
}
### Update Weapon local
PUT http://localhost:3000/weapons/63df0457c255a7f48212822e HTTP/1.1
Content-Type: application/json

{
    "name": "Sleeper Simulant",
    "gunPerkOne": "Corkscrew Rifling",
    "gunPerkTwo": "Alloy Magazine",
    "weaponPerkOne": "Moving Target",
    "weaponPerkTwo": "Composite Stock",
    "masterwork": "Catalyst",
    "originTrait": "false",
    "mod": "something special"
}
### Delete Weapon local
DELETE http://localhost:3000/weapons/63df0457c255a7f48212822e


### Create Weapon Render
POST https://w05-w08.onrender.com/weapons HTTP/1.1
Content-Type: application/json

{
    "firstName":"Emi",
    "lastName":"Tempest",
    "email":"tempest.emi@email.com",
    "favoriteColor":"Purple",
    "birthday":"01/19/2013"
}
### Update Weapon Render
PUT https://w05-w08.onrender.com/weapons/63cae80cb43129ce4cdf1258 HTTP/1.1
Content-Type: application/json

{
    "name": "Sleeper Simulant",
    "gunPerkOne": "Corkscrew Rifling",
    "gunPerkTwo": "Alloy Magazine",
    "weaponPerkOne": "Moving Target",
    "weaponPerkTwo": "Composite Stock",
    "masterwork": "Catalyst",
    "originTrait": false,
    "mod": "somthing special"
}
### Delete Weapon Render
DELETE https://w05-w08.onrender.com/weapons/63cae80cb43129ce4cdf1258